apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-dev
  template:
    metadata:
      labels:
        app: flask-dev
    spec:
      containers:
        - name: flask
          image: us-central1-docker.pkg.dev/cloud-computing-project-ece-1/flask-repo/flask-app
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: mysql-service-dev
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: password
            - name: DB_NAME
              value: crud_db